baseURL = "/"
title = "Zach Stoebner | ECE PhD @ UT Austin"
enableRobotsTXT = true # Suggested, enable robots.txt file
# pygmentsCodefences = true
# pygmentsUseClasses = true
languageCode = "en-US" # Controls site language
paginate = 10 # Number of posts to show before paginating
copyright = "Copyright &copy; Zachary Stoebner. Licensed under <a target=\"_blank\" rel=\"external noopener license\" href=\"https://creativecommons.org/licenses/by-nd/4.0/\">CC-BY-ND-4.0</a>." # Optional, remove to suppress copyright notices

# sets Google Analytics Property stream token for analytics template called in baseof.html
googleAnalytics = "G-CLGDWRWCBJ"

# Controls default theme and theme components
theme = [
  "fractal-forest", # OBSD
  "after-dark" # AGPL-3.0-or-later
]

disableLiveReload = false # Optional, set true to disable live reload
sectionPagesMenu = "main" # Enable menu system for lazy bloggers

[markup.goldmark.renderer]
  unsafe = true # Optional, allows HTML inside your CommonMark content
[markup.tableOfContents]
  startLevel = 1 # Suggested, draws TOC using all heading levels
  endLevel = 6 # Suggested, draws TOC using all heading levels
[markup.highlight]
  noClasses = false # Suggested, used for custom syntax highlighting

[params]
  powered_by = false
  show_menu = true
  description = "Zach Stoebner's personal portfolio website" # Suggested, controls default description meta
  author = "Zach Stoebner" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  disable_csp = false # Optional, set true to disable content security policy
  images = [
    "https://source.unsplash.com/collection/983219/2000x1322"
  ] # Suggested, controls default Open Graph images
  related_content_limit = 5 # limit to 5 items maximum site-wide
  latest_count = 3

[params.hackcss]
  disabled = false # disable skin styles entirely
[params.layout.menu.main]
  hidden = false # Optional, set false or remove to show section menu

[params.layout.footer]
  hidden = false # Optional, set true to hide footer

[params.layout.header]
  hidden = false # Optional, set true to hide header

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation

### SECTIONS
# [params.layout.project.featured]
#  limit = 3
#  items = [
#    "stone-anno",
#    "tello-slam",
#    "cortical-surface-analysis"
#  ]

# [params.layout.project.related]
#   limit = 5
#   thumbs = ["resize", "150x150"] # Optional, thumbnail image processing

# [params.layout.note.featured]
#  limit = 3
#  items = [
#    "haiku-senryu",
#    "fast-inv-sqrt",
#    "hendiadys"
#  ]

# [params.layout.note.related]
#   limit = 5
#   thumbs = ["resize", "150x150"] # Optional, thumbnail image processing

# [params.layout.ku.featured]
#  limit = 3
#  items = [
#    "portugues",
#    "spring-summer-2020",
#    "spring-summer-2019"
#  ]

# [params.layout.ku.related]
#  limit = 5
#  thumbs = ["resize", "150x150"] # Optional, thumbnail image processing

### HOMEPAGE
[params.layout.home]
   hide_blog = true

[[params.layout.home.section]]
type = "about"
weight = 1

[[params.layout.home.section]]
type = "research"
weight = 2

[[params.layout.home.section]]
type = "news"
weight = 3

# [[params.layout.home.section]]
#  type = "projects"
#  weight = 2
#  limit = 3
#  thumbs = ["fill", "400x400"]

# [[params.layout.home.section]]
#  type = "notes"
#  weight = 3
#  limit = 3
#  thumbs = ["fill", "400x400"]

# [[params.layout.home.section]]
# type = "kus"
# weight = 4
# limit = 3
# thumbs = ["fill", "400x400"]

### MENU
[[menu.main]]
  name = "about"
  weight = 1
  identifier = "about"
  url = "/"

# [[menu.main]]
#   name = "projects"
#   weight = 3
#   identifier = "projects"
#   url = "/projects/"

[[menu.main]]
  name = "notes"
  weight = 4
  identifier = "notes"
  url = "/notes/"

[[menu.main]]
  name = "kū"
  weight = 5
  identifier = "kus"
  url = "/kus/"
